### PR TITLE
Issue #168: Upgrade to Angular 8

### PR DESCRIPTION
**Pull request by kamaruzzaman**
Upgrade to Angular 8

### CODE REVIEW

**Comment by bostondevin** [comment]
What's up with this? We're waiting to upgrade to Angular 8

**Comment by kamaruzzaman** [comment]
I am still waiting for the owners to merge my branch into master.

**Comment by chico1198** [comment]
Can anyone at 2muchcoffeecom please merge this? We are in the process of upgrading to Angular 8 and could use this. Thanks.

**Comment by stbn694** [comment]
Please merge this, or I'll have to downgrade my project to Angular 7

**Comment by rshchpkn** [comment]
Hi guys, Thanks for the PR and your patience, version for angular 8 is available under `rc` tag
`npm install ngx-restangular@rc` - command to install tagged version. We will try to test and publish the `latest` version asap

**Pull request merged**
